Update docker images

diff --git a/packaging/docker/Dockerfile b/packaging/docker/Dockerfile
--- a/packaging/docker/Dockerfile
+++ b/packaging/docker/Dockerfile
@@ -16,38 +16,19 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-FROM docker.io/rockylinux/rockylinux:9.4-minimal AS base
-
-RUN microdnf install -y \
-    bind-utils \
-    binutils \
-    curl \
-    gdb \
-    hostname \
-    jq \
-    less \
-    libubsan \
-    lsof \
-    net-tools \
-    nmap-ncat \
-    perf \
-    perl \
-    procps-ng \
-    strace \
-    sysstat \
-    tar \
-    tcpdump \
-    telnet \
-    traceroute \
-    unzip \
-    openssl \
-    vim-enhanced && \
-    microdnf clean all
+FROM docker.palantir.build/ubuntu-nano-installer:u22.04-11202 AS base
 
 WORKDIR /tmp
 
 ARG TARGETARCH
-RUN curl -Ls "https://github.com/krallin/tini/releases/download/v0.19.0/tini-$TARGETARCH" -o "tini-$TARGETARCH"  && \
+ARG FDB_VERSION=7.3.69
+ARG FDB_LIBRARY_VERSIONS="${FDB_VERSION}"
+ARG FDB_WEBSITE=https://artifactory.palantir.build/artifactory/external-dist-github-com/apple/foundationdb/releases/download
+
+RUN apt-get update && \
+    apt-get install -y curl
+
+RUN curl -Ls "https://artifactory.palantir.build/artifactory/external-dist-github-com/krallin/tini/releases/download/v0.19.0/tini-$TARGETARCH" -o "tini-$TARGETARCH"  && \
     echo "93dcc18adc78c65a028a84799ecf8ad40c936fdfc5f2a57b1acda5a8117fa82c  tini-amd64" > "tini-amd64-sha.txt" && \
     echo "07952557df20bfd2a95f9bef198b445e006171969499a1d361bd9e6f8e5e0e81  tini-arm64" > "tini-arm64-sha.txt" && \
     sha256sum --quiet -c "tini-${TARGETARCH}-sha.txt" && \
@@ -55,25 +36,61 @@ RUN curl -Ls "https://github.com/krallin/tini/releases/download/v0.19.0/tini-$TA
     mv "tini-$TARGETARCH" /usr/bin/tini && \
     rm -rf /tmp/*
 
+COPY website /tmp/website/
+
+# Install FoundationDB Binaries and additional FoundationDB Client Libraries
+# We need to do this here so we have access to curl
+RUN if [ "$TARGETARCH" = "amd64" ]; then \
+        FDB_ARCH=x86_64; \
+    elif [ "$TARGETARCH" = "arm64" ]; then \
+        FDB_ARCH=aarch64; \
+    else \
+        echo "ERROR: unsupported architecture $TARGETARCH" 1>&2; \
+        exit 1; \
+    fi; \
+    mkdir -p /downloads/bin /downloads/lib /downloads/multiversion && \
+    CURL="curl --fail -Ls"; \
+    for file in fdbserver fdbbackup fdbcli fdbmonitor; do \
+        URL="${FDB_WEBSITE}/${FDB_VERSION}/$file.$FDB_ARCH"; \
+        echo "Downloading $URL"; \
+        TARGET="/downloads/bin/$file"; \
+        $CURL "$URL" -o "$TARGET" && \
+        chmod +x "$TARGET"; \
+    done && \
+    for version in $FDB_LIBRARY_VERSIONS; do \
+        URL="${FDB_WEBSITE}/${version}/libfdb_c.${FDB_ARCH}.so"; \
+        echo "Downloading $URL"; \
+        TARGET="/downloads/multiversion/libfdb_c_${version%.*}.so"; \
+        $CURL "$URL" -o "$TARGET"; \
+    done && \
+    $CURL $FDB_WEBSITE/$FDB_VERSION/libfdb_c.${FDB_ARCH}.so -o /downloads/lib/libfdb_c.so
+
+
 WORKDIR /
 
-FROM docker.io/library/golang:1.24.6-bookworm AS go-build
+FROM hub.docker.palantir.build/library/golang:1.24.6-bookworm AS go-build
 COPY fdbkubernetesmonitor/ /fdbkubernetesmonitor
 WORKDIR /fdbkubernetesmonitor
 RUN go build -o /fdb-kubernetes-monitor *.go
 
-FROM base AS foundationdb-base
+FROM docker.palantir.build/ubuntu-nano:u22.04-11202 AS foundationdb-base
+
+COPY --from=base /usr/bin/tini /usr/bin/tini
 
 ARG FDB_VERSION=6.3.22
-ARG FDB_LIBRARY_VERSIONS="${FDB_VERSION}"
-ARG FDB_WEBSITE=https://github.com/apple/foundationdb/releases/download
 
-RUN mkdir -p /var/fdb/{logs,tmp,lib} && \
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    mkdir -p /var/fdb/{logs,tmp,lib} && \
     mkdir -p /usr/lib/fdb/multiversion && \
     echo ${FDB_VERSION} > /var/fdb/version
 
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    apt-get update && apt-get install pkg-config libc6 liblzma5 -y --no-install-recommends && \
+    apt-get clean
+
 # Set up a non-root user
-RUN groupadd --gid 4059 \
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    groupadd --gid 4059 \
              fdb && \
     useradd --gid 4059 \
             --uid 4059 \
@@ -83,41 +100,25 @@ RUN groupadd --gid 4059 \
     chown -R fdb:fdb /var/fdb
 
 WORKDIR /tmp
-COPY website /tmp/website/
 
-# Install FoundationDB Binaries and additional FoundationDB Client Libraries
-RUN if [ "$TARGETARCH" = "amd64" ]; then \
-        FDB_ARCH=x86_64; \
-    elif [ "$TARGETARCH" = "arm64" ]; then \
-        FDB_ARCH=aarch64; \
-    else \
-        echo "ERROR: unsupported architecture $TARGETARCH" 1>&2; \
-        exit 1; \
-    fi; \
-    CURL="curl --fail -Ls"; \
-    for file in fdbserver fdbbackup fdbcli fdbmonitor; do \
-        URL="${FDB_WEBSITE}/${FDB_VERSION}/$file.$FDB_ARCH"; \
-        echo "Downloading $URL"; \
-        $CURL "$URL" -o "$file" && \
-        chmod +x "$file" && \
-        mv "$file" /usr/bin/ || exit $?; \
-    done && \
-    mkdir -p /var/fdb/lib && \
-    for version in $FDB_LIBRARY_VERSIONS; do \
-        URL="${FDB_WEBSITE}/${version}/libfdb_c.${FDB_ARCH}.so"; \
-        echo "Downloading $URL"; \
-        TARGET="/usr/lib/fdb/multiversion/libfdb_c_${version%.*}.so"; \
-        $CURL "$URL" -o "$TARGET" && \
-        cp "$TARGET" /var/fdb/lib/ || exit $?; \
-    done && \
-    $CURL $FDB_WEBSITE/$FDB_VERSION/libfdb_c.${FDB_ARCH}.so -o /usr/lib/libfdb_c.so
+# Copy over the FDB binaries and libraries
+COPY --from=base /downloads/bin/* /usr/bin/
+COPY --from=base /downloads/lib/* /usr/lib/
+COPY --from=base /downloads/multiversion/* /var/fdb/lib/
+COPY --from=base /downloads/multiversion/* /usr/lib/fdb/multiversion/
 
 # Setup all symlinks for the other binaries that are a copy of fdbbackup
-RUN for file in fdbdr fdbrestore backup_agent dr_agent fastrestore_tool; do \
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    for file in fdbdr fdbrestore backup_agent dr_agent fastrestore_tool; do \
         ln -s /usr/bin/fdbbackup "/usr/bin/$file"; \
     done && \
     cd / && \
     rm -rf /tmp/*
+
+# ubuntu-nano has very restrictive default folder permissions. We need to allow the fdb user to be able to access the
+# /var/log/fdb-trace-logs folder.
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    chmod o+x /var/log
 
 WORKDIR /
 
@@ -139,38 +140,33 @@ FROM foundationdb-base AS foundationdb-kubernetes-sidecar
 # with the installed openssl version. Since the sidecar support will be deprecated in the
 # future it's fine to use python 3.9 here.
 # EOL for python 3.9 is 2025-10: https://devguide.python.org/versions/
-RUN microdnf -y install \
-    python3.9 \
-    python3.9-pip && \
-    microdnf clean all && \
-    update-alternatives --install /usr/bin/python python /usr/bin/python3.9 20 && \
-    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 20 && \
-    python3 -m pip install watchdog==4.0.1
+
+# We need to remove python3-pip to avoid several CVE
+# We also upgrade from 3.9 to 3.10, since 3.9 is close to EOL
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    apt-get update && apt-get install -y \
+        python3.10 python3-pip && \
+    apt-get clean && \
+    python3.10 -m pip install watchdog==4.0.1 && \
+    apt-get remove python3-pip
 
 WORKDIR /
-ADD entrypoint.bash sidecar.py /
-RUN chmod a+x /entrypoint.bash /sidecar.py
+COPY sidecar.py /
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    chmod a+x /sidecar.py
 USER fdb
 VOLUME /var/input-files
 VOLUME /var/output-files
 ENV LISTEN_PORT=8080
-ENTRYPOINT ["/usr/bin/tini", "-g", "--", "/entrypoint.bash"]
+ENTRYPOINT ["/usr/bin/tini", "-g", "--", "/sidecar.py"]
 
 FROM foundationdb-base AS foundationdb
 
-WORKDIR /tmp
-RUN curl -LsO https://raw.githubusercontent.com/brendangregg/FlameGraph/90533539b75400297092f973163b8a7b067c66d3/stackcollapse-perf.pl && \
-    curl -LsO https://raw.githubusercontent.com/brendangregg/FlameGraph/90533539b75400297092f973163b8a7b067c66d3/flamegraph.pl && \
-    echo "a682ac46497d6fdbf9904d1e405d3aea3ad255fcb156f6b2b1a541324628dfc0  flamegraph.pl" > flamegraph-sha.txt && \
-    echo "5bcfb73ff2c2ab7bf2ad2b851125064780b58c51cc602335ec0001bec92679a5  stackcollapse-perf.pl" >> flamegraph-sha.txt && \
-    sha256sum --quiet -c flamegraph-sha.txt && \
-    chmod +x stackcollapse-perf.pl flamegraph.pl && \
-    mv stackcollapse-perf.pl flamegraph.pl /usr/bin && \
-    rm -rf /tmp/*
 WORKDIR /
 # Set Up Runtime Scripts and Directories
 ADD fdb.bash fdb_single.bash /var/fdb/scripts/
-RUN chmod a+x /var/fdb/scripts/fdb.bash /var/fdb/scripts/fdb_single.bash
+RUN --mount=type=bind,from=base,source=/,target=/installer/ \
+    chmod a+x /var/fdb/scripts/fdb.bash /var/fdb/scripts/fdb_single.bash
 VOLUME /var/fdb/data
 ENV FDB_PORT=4500
 ENV FDB_CLUSTER_FILE=/var/fdb/fdb.cluster
@@ -182,6 +178,8 @@ ENV FDB_PROCESS_CLASS=unset
 ENTRYPOINT ["/usr/bin/tini", "-g", "--", "/var/fdb/scripts/fdb.bash"]
 
 FROM foundationdb-base AS ycsb
+# This stage is only used for load tests, which is not part of our build pipeline.
+# This stage is broken, since the commands are still for rocky linux but we are now based on ubuntu.
 
 RUN microdnf -y install \
     java-11-openjdk java-11-openjdk-devel && \
